application:
  runtimeManifest:
    packages:
      mock-reviews-api:
        function: actions/reviews/mock-api/index.js
        web: "yes"
        runtime: nodejs:22
        inputs:
          LOG_LEVEL: debug
          GC_GRAPHQL_ENDPOINT: $GC_GRAPHQL_ENDPOINT
          GC_CLIENT_ID_REVIEW: $GC_CLIENT_ID_REVIEW
        annotations:
          require-adobe-auth: false
          final: true
